/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/Account': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          userId?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['AccountPublicInfoResponse']
            'application/json': components['schemas']['AccountPublicInfoResponse']
            'text/json': components['schemas']['AccountPublicInfoResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['AccountFullInfoResponse']
            'application/json': components['schemas']['AccountFullInfoResponse']
            'text/json': components['schemas']['AccountFullInfoResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/friends': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['FriendsSummary']
            'application/json': components['schemas']['FriendsSummary']
            'text/json': components['schemas']['FriendsSummary']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/friends/all': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SplitPageFriendsCommand']
          'text/json': components['schemas']['SplitPageFriendsCommand']
          'application/*+json': components['schemas']['SplitPageFriendsCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['SplitFriendsArrayResponse']
            'application/json': components['schemas']['SplitFriendsArrayResponse']
            'text/json': components['schemas']['SplitFriendsArrayResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/friends/online': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SplitPageFriendsCommand']
          'text/json': components['schemas']['SplitPageFriendsCommand']
          'application/*+json': components['schemas']['SplitPageFriendsCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['SplitFriendsArrayResponse']
            'application/json': components['schemas']['SplitFriendsArrayResponse']
            'text/json': components['schemas']['SplitFriendsArrayResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/friends/recent': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SplitPageFriendsCommand']
          'text/json': components['schemas']['SplitPageFriendsCommand']
          'application/*+json': components['schemas']['SplitPageFriendsCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['SplitFriendsArrayResponse']
            'application/json': components['schemas']['SplitFriendsArrayResponse']
            'text/json': components['schemas']['SplitFriendsArrayResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/social/pending': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['NewFriendRequest'][]
            'application/json': components['schemas']['NewFriendRequest'][]
            'text/json': components['schemas']['NewFriendRequest'][]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/social/logs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['RecentActivityLog'][]
            'application/json': components['schemas']['RecentActivityLog'][]
            'text/json': components['schemas']['RecentActivityLog'][]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/social/dealRequest/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: {
      parameters: {
        query?: {
          targetUserId?: number | string
          confirm?: boolean
        }
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/social/sendRequest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: {
      parameters: {
        query?: {
          targetUserId?: number | string
        }
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/social/collectTags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': string[]
            'application/json': string[]
            'text/json': string[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Account/social/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SearchFriendsCommand']
          'text/json': components['schemas']['SearchFriendsCommand']
          'application/*+json': components['schemas']['SearchFriendsCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['AccountPublicInfoResponse'][]
            'application/json': components['schemas']['AccountPublicInfoResponse'][]
            'text/json': components['schemas']['AccountPublicInfoResponse'][]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Buildings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['BuildingSummaryResponse']
            'application/json': components['schemas']['BuildingSummaryResponse']
            'text/json': components['schemas']['BuildingSummaryResponse']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: {
          Page?: number | string
          PageSize?: number | string
          Searches?: string[]
          Provinces?: string[]
          Categories?: string[]
          Dynasties?: string[]
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['SplitPageResponse']
            'application/json': components['schemas']['SplitPageResponse']
            'text/json': components['schemas']['SplitPageResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDetails']
            'application/json': components['schemas']['ValidationProblemDetails']
            'text/json': components['schemas']['ValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Buildings/{hash}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          hash: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['BuildingArticle']
            'application/json': components['schemas']['BuildingArticle']
            'text/json': components['schemas']['BuildingArticle']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Buildings/name/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          name: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Found */
        302: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Forum/post': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ForumSummaryResponse']
            'application/json': components['schemas']['ForumSummaryResponse']
            'text/json': components['schemas']['ForumSummaryResponse']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Forum/post/{postId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          postId: number | string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Forum/publish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Secure/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 注册账号 */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthRegisterCommand']
          'text/json': components['schemas']['AuthRegisterCommand']
          'application/*+json': components['schemas']['AuthRegisterCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['AuthRegisterResponse']
            'application/json': components['schemas']['AuthRegisterResponse']
            'text/json': components['schemas']['AuthRegisterResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDetails']
            'application/json': components['schemas']['ValidationProblemDetails']
            'text/json': components['schemas']['ValidationProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Secure/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 帐号密码登陆账号 */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthLoginCommand']
          'text/json': components['schemas']['AuthLoginCommand']
          'application/*+json': components['schemas']['AuthLoginCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['AuthLoginResponse']
            'application/json': components['schemas']['AuthLoginResponse']
            'text/json': components['schemas']['AuthLoginResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDetails']
            'application/json': components['schemas']['ValidationProblemDetails']
            'text/json': components['schemas']['ValidationProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Secure/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 刷新AccessToken */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['RefreshTokenCommand']
          'text/json': components['schemas']['RefreshTokenCommand']
          'application/*+json': components['schemas']['RefreshTokenCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['RefreshTokenResponse']
            'application/json': components['schemas']['RefreshTokenResponse']
            'text/json': components['schemas']['RefreshTokenResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDetails']
            'application/json': components['schemas']['ValidationProblemDetails']
            'text/json': components['schemas']['ValidationProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Secure/changeEmail': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 修改账号绑定邮箱 */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthChangeEmailCommand']
          'text/json': components['schemas']['AuthChangeEmailCommand']
          'application/*+json': components['schemas']['AuthChangeEmailCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDetails']
            'application/json': components['schemas']['ValidationProblemDetails']
            'text/json': components['schemas']['ValidationProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Secure/changePassword': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 获取修改账号密码单次临时验证码 */
    get: {
      parameters: {
        query?: never
        header?: {
          userId?: number | string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    /** 修改账号密码 */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthChangePasswordCommand']
          'text/json': components['schemas']['AuthChangePasswordCommand']
          'application/*+json': components['schemas']['AuthChangePasswordCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDetails']
            'application/json': components['schemas']['ValidationProblemDetails']
            'text/json': components['schemas']['ValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/Secure/resetPassword': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 获取重置账号单次临时验证码 */
    get: {
      parameters: {
        query?: never
        header?: {
          email?: string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    /** 重置账号密码 */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthResetPasswordCommand']
          'text/json': components['schemas']['AuthResetPasswordCommand']
          'application/*+json': components['schemas']['AuthResetPasswordCommand']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDetails']
            'application/json': components['schemas']['ValidationProblemDetails']
            'text/json': components['schemas']['ValidationProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDetails']
            'application/json': components['schemas']['ValidationProblemDetails']
            'text/json': components['schemas']['ValidationProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AccountFullInfoResponse: {
      /** Format: int64 */
      userId: number | string
      userName: string
      profile: string
      location: string
      gender?: string
      interest?: string[]
      online: boolean
    }
    AccountPublicInfoResponse: {
      /** Format: int64 */
      userId: number | string
      userName: string
      profile: string
      location: string
      gender?: string
      interest?: string[]
    }
    ArrayPair: {
      /** Format: int32 */
      length?: number | string
      values?: string[]
    }
    AuthChangeEmailCommand: {
      /** Format: int64 */
      userId: number | string
      newEmail: string
    }
    AuthChangePasswordCommand: {
      /** Format: int64 */
      userId: number | string
      newPassword: string
      confirmKey: string
    }
    AuthLoginCommand: {
      email: string
      hash: string
      password: string
    }
    AuthLoginResponse: {
      /** Format: int64 */
      userId: number | string
      email: string
      accessToken: string
      /** Format: date-time */
      accessTokenExpire: string
      refreshToken: string
      /** Format: date-time */
      refreshTokenExpire: string
    }
    AuthRegisterCommand: {
      email: string
      password: string
      username: string
    }
    AuthRegisterResponse: {
      /** Format: int64 */
      userId: number | string
      email: string
      username: string
      /** Format: date-time */
      createdAt: string
    }
    AuthResetPasswordCommand: {
      email: string
      confirmKey: string
      password: string
      newPassword: string
    }
    BuildingArticle: {
      img: string
      title: string
      provinces: string[]
      dynasties: string[]
      categories: string[]
      name: string
      desc: string
      subtitle: string
      id: string
      body: components['schemas']['JsonDocument']
    }
    BuildingSlug: {
      hash: string
      name: string
      desc: string
      img: string
      provinces: string[]
      categories: string[]
      dynasties: string[]
    }
    BuildingSummaryResponse: {
      provinces?: components['schemas']['ArrayPair']
      categories?: components['schemas']['ArrayPair']
      dynasties?: components['schemas']['ArrayPair']
      /** Format: int32 */
      total?: number | string
    }
    ForumSummaryResponse: Record<string, never>
    FriendInfo: {
      /** Format: int64 */
      userId: number | string
      userName: string
      profile?: string
      location?: string
      interest?: string[]
    }
    FriendsSummary: {
      /** Format: int32 */
      total?: number | string
      /** Format: int32 */
      online?: number | string
      /** Format: int32 */
      request?: number | string
    }
    JsonDocument: unknown
    NewFriendRequest: {
      /** Format: int64 */
      userId?: number | string
      userName?: string
      createdAt?: string
    }
    ProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
    }
    RecentActivityLog: {
      /** Format: int64 */
      userId?: number | string
      userName?: string
      decs?: string
      avatar?: string
      url?: null | string
    }
    RefreshTokenCommand: {
      /** Format: int64 */
      userId: number | string
      email: string
      hash: string
      refreshToken: string
    }
    RefreshTokenResponse: {
      /** Format: int64 */
      userId: number | string
      accessToken: string
      /** Format: date-time */
      accessTokenExpire: string
    }
    SearchFriendsCommand: {
      /** Format: int32 */
      page?: number | string
      searchTags?: string[]
      searches?: string[]
    }
    SplitFriendsArrayResponse: {
      users?: components['schemas']['FriendInfo'][]
      /** Format: int32 */
      count?: number | string
    }
    SplitPageFriendsCommand: {
      /** Format: int32 */
      page: number | string
      search: string
    }
    SplitPageResponse: {
      items?: components['schemas']['BuildingSlug'][]
      /** Format: int32 */
      total?: number | string
    }
    ValidationProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
      errors?: {
        [key: string]: string[]
      }
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
